<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_Login_Functionality</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>10cdfedb-d0ff-4af2-9699-53d3ab9a5227</testSuiteGuid>
   <testCaseLink>
      <guid>6aa00faf-f28f-4193-9fc8-d09cec82fc43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify_Blank_Username_Message</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29a589f9-0c31-4c69-9e5a-623edaba810f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdb51235-189a-415c-b9b3-c2e39811df66</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94d5c397-d1ca-4bed-84dd-10dd4f0cea4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify_Invalid_Username_Message</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b312d36-df0f-4f22-b96d-e207b33821b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>580c6805-f19f-4c4c-aaea-f68d76e08191</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a13580e-1ff5-4346-a76c-e6d205ba60fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify_Forgot_Your_Password_Link</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20efc6b7-c7e4-4fa2-a959-f4e75e36c0b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74da6331-cc8a-410e-8910-8e52bf5fa5f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d1c5e5c1-cc76-43a6-8449-a22ae889a252</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify_Create_An_Account</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7045522-a200-46b8-8cc4-386767dd4cb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf8023c3-3169-4d32-accc-689af865c80f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc4d93eb-7184-4cd5-8d9c-ff72bf25757b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify_Contact_Us_Link</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f87185aa-cd73-4937-84b2-78ccb64a682e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fca9b61b-a324-4e2f-9f9f-ea92b6a3aa6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>773b1a35-29bf-42bb-a183-f1a5f5d175aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify_Home_Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c64c67f4-e180-455a-a1b3-6ca7a507ea75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ac01f6a-01dd-44e9-bcd5-158d17759ece</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
